spring.config.import=optional:file:./.env[.properties],optional:file:./CardService/.env[.properties]

spring.application.name=${CARD_NAME}
server.port=${CARD_PORT}
grpc.server.port=${CARD_GRPC_PORT}

spring.datasource.url=${CARD_SPRING_DATASOURCE_URL}
spring.datasource.username=${CARD_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${CARD_SPRING_DATASOURCE_PASSWORD}
