services:
  postgres:
    image: postgres:16
    container_name: auth-postgres
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ../AuthService
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        PORT: ${AUTH_PORT}
    container_name: auth-service
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    depends_on:
      - postgres
    environment:
      AUTH_NAME: ${AUTH_NAME}
      AUTH_PORT: ${AUTH_PORT}
      AUTH_GRPC_PORT: ${AUTH_GRPC_PORT}
      SPRING_DATASOURCE_URL: ${AUTH_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${AUTH_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_SPRING_DATASOURCE_PASSWORD}

  api-gateway:
    build:
      context: ../ApiGateway
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        PORT: ${API_GATEWAY_PORT}
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    depends_on:
      - auth-service
    environment:
      API_GATEWAY_NAME: ${API_GATEWAY_NAME}
      API_GATEWAY_PORT: ${API_GATEWAY_PORT}
      AUTH_GRPC_HOST: ${AUTH_GRPC_HOST}
      AUTH_GRPC_PORT: ${AUTH_GRPC_PORT}

volumes:
  postgres_data:
