services:
  auth-postgres:
    image: postgres:16
    container_name: auth-postgres
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
    ports:
      - "${AUTH_POSTGRES_PORT}:${AUTH_POSTGRES_PORT}"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ../AuthService
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        PORT: ${AUTH_PORT}
    container_name: auth-service
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    depends_on:
      - auth-postgres
    environment:
      AUTH_NAME: ${AUTH_NAME}
      AUTH_PORT: ${AUTH_PORT}
      AUTH_GRPC_PORT: ${AUTH_GRPC_PORT}
      SPRING_DATASOURCE_URL: ${AUTH_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${AUTH_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_SPRING_DATASOURCE_PASSWORD}

  user-postgres:
    image: postgres:16
    container_name: user-postgres
    environment:
      POSTGRES_DB: ${USER_POSTGRES_DB}
      POSTGRES_USER: ${USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_PASSWORD}
    ports:
      - "${USER_POSTGRES_PORT}:${USER_POSTGRES_PORT}"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ../UserService
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        PORT: ${USER_PORT}
    container_name: user-service
    ports:
      - "${USER_PORT}:${USER_PORT}"
    depends_on:
      - user-postgres
    environment:
      USER_NAME: ${USER_NAME}
      USER_PORT: ${USER_PORT}
      USER_GRPC_PORT: ${USER_GRPC_PORT}
      SPRING_DATASOURCE_URL: ${USER_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${USER_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${USER_SPRING_DATASOURCE_PASSWORD}

  account-postgres:
    image: postgres:16
    container_name: account-postgres
    environment:
      POSTGRES_DB: ${ACCOUNT_POSTGRES_DB}
      POSTGRES_USER: ${ACCOUNT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ACCOUNT_POSTGRES_PASSWORD}
    ports:
      - "${ACCOUNT_POSTGRES_PORT}:${ACCOUNT_POSTGRES_PORT}"
    volumes:
      - account_postgres_data:/var/lib/postgresql/data

  account-service:
    build:
      context: ../AccountService
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        PORT: ${ACCOUNT_PORT}
    container_name: account-service
    ports:
      - "${ACCOUNT_PORT}:${ACCOUNT_PORT}"
    depends_on:
      - account-postgres
    environment:
      ACCOUNT_NAME: ${ACCOUNT_NAME}
      ACCOUNT_PORT: ${ACCOUNT_PORT}
      ACCOUNT_GRPC_PORT: ${ACCOUNT_GRPC_PORT}
      SPRING_DATASOURCE_URL: ${ACCOUNT_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${ACCOUNT_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${ACCOUNT_SPRING_DATASOURCE_PASSWORD}

  card-postgres:
    image: postgres:16
    container_name: card-postgres
    environment:
      POSTGRES_DB: ${CARD_POSTGRES_DB}
      POSTGRES_USER: ${CARD_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CARD_POSTGRES_PASSWORD}
    ports:
      - "${CARD_POSTGRES_PORT}:${CARD_POSTGRES_PORT}"
    volumes:
      - card_postgres_data:/var/lib/postgresql/data

  card-service:
    build:
      context: ../CardService
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        PORT: ${CARD_PORT}
    container_name: card-service
    ports:
      - "${CARD_PORT}:${CARD_PORT}"
    depends_on:
      - card-postgres
    environment:
      CARD_NAME: ${CARD_NAME}
      CARD_PORT: ${CARD_PORT}
      CARD_GRPC_PORT: ${CARD_GRPC_PORT}
      SPRING_DATASOURCE_URL: ${CARD_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${CARD_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${CARD_SPRING_DATASOURCE_PASSWORD}

  transaction-postgres:
    image: postgres:16
    container_name: transaction-postgres
    environment:
      POSTGRES_DB: ${TRANSACTION_POSTGRES_DB}
      POSTGRES_USER: ${TRANSACTION_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TRANSACTION_POSTGRES_PASSWORD}
    ports:
      - "${TRANSACTION_POSTGRES_PORT}:5432"
    volumes:
      - transaction_postgres_data:/var/lib/postgresql/data

  transaction-service:
    build:
      context: ../TransactionService
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        PORT: ${TRANSACTION_PORT}
    container_name: transaction-service
    ports:
      - "${TRANSACTION_PORT}:${TRANSACTION_PORT}"
    depends_on:
      - transaction-postgres
    environment:
      TRANSACTION_NAME: ${TRANSACTION_NAME}
      TRANSACTION_PORT: ${TRANSACTION_PORT}
      TRANSACTION_GRPC_PORT: ${TRANSACTION_GRPC_PORT}
      SPRING_DATASOURCE_URL: ${TRANSACTION_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${TRANSACTION_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${TRANSACTION_SPRING_DATASOURCE_PASSWORD}

  notification-postgres:
    image: postgres:16
    container_name: notification-postgres
    environment:
      POSTGRES_DB: ${NOTIFICATION_POSTGRES_DB}
      POSTGRES_USER: ${NOTIFICATION_POSTGRES_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_POSTGRES_PASSWORD}
    ports:
      - "${NOTIFICATION_POSTGRES_PORT}:5432"
    volumes:
      - notification_postgres_data:/var/lib/postgresql/data

  notification-service:
    build:
      context: ../NotificationService
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        PORT: ${NOTIFICATION_PORT}
    container_name: notification-service
    ports:
      - "${NOTIFICATION_PORT}:${NOTIFICATION_PORT}"
    depends_on:
      - notification-postgres
    environment:
      NOTIFICATION_NAME: ${NOTIFICATION_NAME}
      NOTIFICATION_PORT: ${NOTIFICATION_PORT}
      NOTIFICATION_GRPC_PORT: ${NOTIFICATION_GRPC_PORT}
      NOTIFICATION_SPRING_DATASOURCE_URL: ${NOTIFICATION_SPRING_DATASOURCE_URL}
      NOTIFICATION_SPRING_DATASOURCE_USERNAME: ${NOTIFICATION_SPRING_DATASOURCE_USERNAME}
      NOTIFICATION_SPRING_DATASOURCE_PASSWORD: ${NOTIFICATION_SPRING_DATASOURCE_PASSWORD}

  api-gateway:
    build:
      context: ../ApiGateway
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        PORT: ${API_GATEWAY_PORT}
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    depends_on:
      - auth-service
      - user-service
      - account-service
      - card-service
      - transaction-service
      - notification-service
    environment:
      API_GATEWAY_NAME: ${API_GATEWAY_NAME}
      API_GATEWAY_PORT: ${API_GATEWAY_PORT}
      AUTH_GRPC_HOST: ${AUTH_GRPC_HOST}
      AUTH_GRPC_PORT: ${AUTH_GRPC_PORT}
      USER_GRPC_HOST: ${USER_GRPC_HOST}
      USER_GRPC_PORT: ${USER_GRPC_PORT}
      ACCOUNT_GRPC_HOST: ${ACCOUNT_GRPC_HOST}
      ACCOUNT_GRPC_PORT: ${ACCOUNT_GRPC_PORT}
      CARD_GRPC_HOST: ${CARD_GRPC_HOST}
      CARD_GRPC_PORT: ${CARD_GRPC_PORT}
      TRANSACTION_GRPC_HOST: ${TRANSACTION_GRPC_HOST}
      TRANSACTION_GRPC_PORT: ${TRANSACTION_GRPC_PORT}

volumes:
  auth_postgres_data:
  user_postgres_data:
  account_postgres_data:
  card_postgres_data:
  transaction_postgres_data:
  notification_postgres_data:
