services:

  api-gateway:
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        PORT: ${PORT}
    container_name: auth-service
    ports:
      - "${PORT}:${PORT}"
    environment:
      NAME: ${NAME}
      PORT: ${PORT}
      AUTH_GRPC_HOST: ${AUTH_GRPC_HOST}
      AUTH_GRPC_PORT: ${AUTH_GRPC_PORT}

