services:

  api-gateway:
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        PORT: ${API_GATEWAY_PORT}
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    environment:
      API_GATEWAY_NAME: ${API_GATEWAY_NAME}
      API_GATEWAY_PORT: ${API_GATEWAY_PORT}
      AUTH_GRPC_HOST: ${AUTH_GRPC_HOST}
      AUTH_GRPC_PORT: ${AUTH_GRPC_PORT}
