services:
  notification-mongodb:
    image: mongo:7
    container_name: notification-mongodb
    environment:
      MONGO_INITDB_DATABASE: ${NOTIFICATION_MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${NOTIFICATION_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${NOTIFICATION_MONGO_PASSWORD}
    ports:
      - "${NOTIFICATION_MONGO_PORT}:27017"
    volumes:
      - notification_mongo_data:/data/db

  notification-service:
    image: notification-service:${IMAGE_TAG:-dev}
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        PORT: ${NOTIFICATION_PORT}
    container_name: notification-service
    ports:
      - "${NOTIFICATION_PORT}:${NOTIFICATION_PORT}"
      - "${NOTIFICATION_GRPC_PORT}:${NOTIFICATION_GRPC_PORT}"
    depends_on:
      - notification-mongodb
    environment:
      NOTIFICATION_NAME: ${NOTIFICATION_NAME}
      NOTIFICATION_PORT: ${NOTIFICATION_PORT}
      NOTIFICATION_GRPC_PORT: ${NOTIFICATION_GRPC_PORT}
      SITE_URL: ${SITE_URL}
      NOTIFICATION_MONGO_URI: ${NOTIFICATION_MONGO_URI}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

volumes:
  notification_mongo_data:
