spring.config.import=optional:file:./${ENV_FILE:.env.local}[.properties],optional:file:./ApiGateway/${ENV_FILE:.env.local}[.properties]

spring.application.name=${NAME}
server.port=${PORT}

spring.cloud.gateway.server.webmvc.routes[0].id=${AUTH_ROUTE_ID}
spring.cloud.gateway.server.webmvc.routes[0].uri=${AUTH_SERVICE_URI}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=${AUTH_ROUTE_PATHS}

#spring.cloud.gateway.server.webmvc.routes[1].id=${USER_ROUTE_ID:user-service}
#spring.cloud.gateway.server.webmvc.routes[1].uri=${USER_SERVICE_URI:http://localhost:8082}
#spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=${USER_ROUTE_PATHS:/user/**}
#
#spring.cloud.gateway.server.webmvc.routes[2].id=inventory-service
#spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8083
#spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/inventory/**
#
#spring.cloud.gateway.server.webmvc.routes[3].id=product-service
#spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8084
#spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/product/**
#
#spring.cloud.gateway.server.webmvc.routes[4].id=order-service
#spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8085
#spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/order/**
#
#spring.cloud.gateway.server.webmvc.routes[5].id=notification-service
#spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8086
#spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/notification/**
