spring.config.import=optional:file:./${ENV_FILE:.env.local}[.properties],optional:file:./ApiGateway/${ENV_FILE:.env.local}[.properties]

spring.application.name=${API_GATEWAY_NAME}
server.port=${API_GATEWAY_PORT}
