spring.config.import=optional:file:./.env[.properties],optional:file:./AccountService/.env[.properties]

spring.application.name=${ACCOUNT_NAME}
server.port=${ACCOUNT_PORT}
grpc.server.port=${ACCOUNT_GRPC_PORT}

spring.datasource.url=${ACCOUNT_SPRING_DATASOURCE_URL}
spring.datasource.username=${ACCOUNT_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${ACCOUNT_SPRING_DATASOURCE_PASSWORD}
