services:
  card-postgres:
    image: postgres:16
    container_name: card-postgres
    environment:
      POSTGRES_DB: ${CARD_POSTGRES_DB}
      POSTGRES_USER: ${CARD_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CARD_POSTGRES_PASSWORD}
    ports:
      - "${CARD_POSTGRES_PORT}:5432"
    volumes:
      - card_postgres_data:/var/lib/postgresql/data

  card-service:
    image: card-service:${IMAGE_TAG:-dev}
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        PORT: ${CARD_PORT}
    container_name: card-service
    ports:
      - "${CARD_PORT}:${CARD_PORT}"
      - "${CARD_GRPC_PORT}:${CARD_GRPC_PORT}"
    depends_on:
      - card-postgres
    environment:
      CARD_NAME: ${CARD_NAME}
      CARD_PORT: ${CARD_PORT}
      CARD_GRPC_PORT: ${CARD_GRPC_PORT}
      CARD_SPRING_DATASOURCE_URL: ${CARD_SPRING_DATASOURCE_URL}
      CARD_SPRING_DATASOURCE_USERNAME: ${CARD_SPRING_DATASOURCE_USERNAME}
      CARD_SPRING_DATASOURCE_PASSWORD: ${CARD_SPRING_DATASOURCE_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      SCHEMA_REGISTRY_URL: ${SCHEMA_REGISTRY_URL}

volumes:
  card_postgres_data:
