spring.config.import=optional:file:./.env[.properties],optional:file:./UserService/.env[.properties]

spring.application.name=${USER_NAME}
server.port=${USER_PORT}
grpc.server.port=${USER_GRPC_PORT}

spring.datasource.url=${USER_SPRING_DATASOURCE_URL}
spring.datasource.username=${USER_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${USER_SPRING_DATASOURCE_PASSWORD}
