spring.config.import=optional:file:./.env[.properties],optional:file:./UserService/.env[.properties]

spring.application.name=${USER_NAME}
server.port=${USER_PORT}
grpc.server.port=${USER_GRPC_PORT}

spring.datasource.url=${USER_SPRING_DATASOURCE_URL}
spring.datasource.username=${USER_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${USER_SPRING_DATASOURCE_PASSWORD}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.producer.properties.schema.registry.url=${SCHEMA_REGISTRY_URL}

spring.kafka.consumer.group-id=user-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.schema.registry.url=${SCHEMA_REGISTRY_URL}
spring.kafka.consumer.properties.specific.avro.reader=true