spring.config.import=optional:file:./.env[.properties],optional:file:./AuthService/.env[.properties]

spring.application.name=${NAME}
server.port=${PORT}
grpc.server.port=${GRPC_PORT}

spring.datasource.url=${AUTH_SPRING_DATASOURCE_URL}
spring.datasource.username=${AUTH_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${AUTH_SPRING_DATASOURCE_PASSWORD}