spring.config.import=optional:file:./.env[.properties],optional:file:./NotificationService/.env[.properties]

spring.application.name=${NOTIFICATION_NAME}
server.port=${NOTIFICATION_PORT}
grpc.server.port=${NOTIFICATION_GRPC_PORT}

spring.data.mongodb.host=${NOTIFICATION_MONGO_HOST}
spring.data.mongodb.port=${NOTIFICATION_MONGO_PORT}
spring.data.mongodb.database=${NOTIFICATION_MONGO_DB}
spring.data.mongodb.username=${NOTIFICATION_MONGO_USER}
spring.data.mongodb.password=${NOTIFICATION_MONGO_PASSWORD}
spring.data.mongodb.authentication-database=admin
