spring.config.import=optional:file:./.env[.properties],optional:file:./NotificationService/.env[.properties]

spring.application.name=${NOTIFICATION_NAME}
server.port=${NOTIFICATION_PORT}
grpc.server.port=${NOTIFICATION_GRPC_PORT}

spring.datasource.url=${NOTIFICATION_SPRING_DATASOURCE_URL}
spring.datasource.username=${NOTIFICATION_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${NOTIFICATION_SPRING_DATASOURCE_PASSWORD}
