spring.config.import=optional:file:./.env[.properties],optional:file:./NotificationService/.env[.properties]

spring.application.name=${NOTIFICATION_NAME}
server.port=${NOTIFICATION_PORT}
grpc.server.port=${NOTIFICATION_GRPC_PORT}

spring.data.mongodb.uri=${NOTIFICATION_MONGO_URI}
