spring.config.import=optional:file:./.env[.properties],optional:file:./TransactionService/.env[.properties]

spring.application.name=${TRANSACTION_NAME}
server.port=${TRANSACTION_PORT}
grpc.server.port=${TRANSACTION_GRPC_PORT}

spring.datasource.url=${TRANSACTION_SPRING_DATASOURCE_URL}
spring.datasource.username=${TRANSACTION_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${TRANSACTION_SPRING_DATASOURCE_PASSWORD}
