{{- if and .Values.global.jwt.privateKey .Values.global.jwt.publicKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.jwt.secretName }}
type: Opaque
stringData:
  private.pem: |-
{{ .Values.global.jwt.privateKey | indent 4 }}
  public.pem: |-
{{ .Values.global.jwt.publicKey | indent 4 }}
{{- end }}
