services:
  account-postgres:
    image: postgres:16
    container_name: account-postgres
    environment:
      POSTGRES_DB: ${ACCOUNT_POSTGRES_DB}
      POSTGRES_USER: ${ACCOUNT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ACCOUNT_POSTGRES_PASSWORD}
    ports:
      - "${ACCOUNT_POSTGRES_PORT}:${ACCOUNT_POSTGRES_PORT}"
    volumes:
      - account_postgres_data:/var/lib/postgresql/data

  account-service:
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        PORT: ${ACCOUNT_PORT}
    container_name: account-service
    ports:
      - "${ACCOUNT_PORT}:${ACCOUNT_PORT}"
    depends_on:
      - account-postgres
    environment:
      ACCOUNT_NAME: ${ACCOUNT_NAME}
      ACCOUNT_PORT: ${ACCOUNT_PORT}
      ACCOUNT_GRPC_PORT: ${ACCOUNT_GRPC_PORT}
      SPRING_DATASOURCE_URL: ${ACCOUNT_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${ACCOUNT_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${ACCOUNT_SPRING_DATASOURCE_PASSWORD}

volumes:
  account_postgres_data:
