services:
  auth:
    postgres:
      password: replace_me

  user:
    postgres:
      password: replace_me

  account:
    postgres:
      password: replace_me

  card:
    postgres:
      password: replace_me

  transaction:
    postgres:
      password: replace_me

  notification:
    mongo:
      password: replace_me