global:
  imageTag: dev
  imagePullPolicy: IfNotPresent

images:
  auth: auth-service
  user: user-service
  account: account-service
  card: card-service
  transaction: transaction-service
  notification: notification-service
  apiGateway: api-gateway

kafka:
  image: apache/kafka:3.7.0
  containerPort: 9092
  controllerPort: 9093
  bootstrapServers: kafka:9092
  ui:
    enabled: true
    image: provectuslabs/kafka-ui:latest
    containerPort: 8080
    port: 8079
  schemaRegistry:
    enabled: true
    image: confluentinc/cp-schema-registry:7.7.10
    port: 8081
    url: http://schema-registry:8081

jwt:
  secretName: jwt-keys
  privateKeyPath: /secrets/private.pem
  publicKeyPath: /secrets/public.pem
  privateKey: ""
  publicKey: ""

postgres:
  image: postgres:16
  storage: 1Gi

mongo:
  image: mongo:7
  storage: 1Gi

services:
  auth:
    name: auth-service
    port: 8081
    grpcPort: 8090
    postgres:
      host: auth-postgres
      db: auth_db
      user: auth_user
      password: ""

  user:
    name: user-service
    port: 8082
    grpcPort: 8091
    postgres:
      host: user-postgres
      db: user_db
      user: user_user
      password: ""

  account:
    name: account-service
    port: 8083
    grpcPort: 8092
    postgres:
      host: account-postgres
      db: account_db
      user: account_user
      password: ""

  card:
    name: card-service
    port: 8084
    grpcPort: 8093
    postgres:
      host: card-postgres
      db: card_db
      user: card_user
      password: ""

  transaction:
    name: transaction-service
    port: 8085
    grpcPort: 8094
    postgres:
      host: transaction-postgres
      db: transaction_db
      user: transaction_user
      password: ""

  notification:
    name: notification-service
    port: 8086
    grpcPort: 8095
    siteUrl: http://localhost:8080
    mongo:
      host: notification-mongodb
      port: 27017
      db: notification_db
      user: notification_user
      password: ""
      uri: ""
    mail:
      host: smtp.mailgun.org
      port: 587
      username: postmaster@YOUR_DOMAIN
      password: ""

apiGateway:
  name: api-gateway
  port: 8080
  serviceType: NodePort

prometheus:
  image: prom/prometheus:v2.55.1
  port: 9090
  storage: 1Gi
  scrapeInterval: 15s

grafana:
  image: grafana/grafana:11.4.0
  port: 3000
  serviceType: ClusterIP
  storage: 1Gi
  adminUser: admin
  adminPassword: admin

jaeger:
  enabled: true
  name: jaeger
  image: cr.jaegertracing.io/jaegertracing/jaeger:2.20.0
  serviceType: ClusterIP
  uiPort: 16686
  otlpGrpcPort: 4317
  otlpHttpPort: 4318
  samplingPort: 5778
  zipkinPort: 9411
  tracing:
    samplingProbability: "1.0"
    metricsExportEnabled: false

loki:
  image: grafana/loki:3.7.0
  port: 3100
  grpcPort: 9096
  storage: 1Gi
  retention: 168h

alloy:
  image: grafana/alloy:latest
  port: 12345
