services:
  auth:
    postgres:
      password: replace_me

  user:
    postgres:
      password: replace_me

  account:
    postgres:
      password: replace_me

  card:
    postgres:
      password: replace_me

  transaction:
    postgres:
      password: replace_me

  notification:
    mongo:
      password: replace_me
    mail:
      password: replace_me

jwt:
  privateKey: |
    -----BEGIN PRIVATE KEY-----
    replace_me
    -----END PRIVATE KEY-----
  publicKey: |
    -----BEGIN PUBLIC KEY-----
    replace_me
    -----END PUBLIC KEY-----
