services:
  auth-postgres:
    image: postgres:16
    container_name: auth-postgres
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
    ports:
      - "${AUTH_POSTGRES_PORT}:${AUTH_POSTGRES_PORT}"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        PORT: ${AUTH_PORT}
    container_name: auth-service
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    depends_on:
      - auth-postgres
    environment:
      AUTH_NAME: ${AUTH_NAME}
      AUTH_PORT: ${AUTH_PORT}
      AUTH_GRPC_PORT: ${AUTH_GRPC_PORT}
      SPRING_DATASOURCE_URL: ${AUTH_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${AUTH_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_SPRING_DATASOURCE_PASSWORD}

volumes:
  auth_postgres_data:
